### ISSUE TITLE
insert function deprecated with warning for pymongo

### ISSUE THREAD

**Issue by xialu4820723** [mdomke/humongous#15]
warning message:  
`DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.`

**Comment by mdomke** [comment]
@xialu4820723 `pytest-mongodb` doesn't provide any functionality with respect to mocking MongoDB itself, but uses `mongomock` for that purpose. On the other hand I'm just guessing what you're trying to tell me. Could you be more specific on the details of the issue?

**Comment by xialu4820723** [comment]
During fixture loading, `insert` method was used, [source code](https://github.com/mdomke/pytest-mongodb/blob/develop/pytest_mongodb/plugin.py#L112), 
which was deprecated by pymongo from 3.0, [source code](https://github.com/mongodb/mongo-python-driver/blob/7f1939ebcb6f577f762bf5cd068288d2533b2bbf/pymongo/collection.py#L3155), warning messages will be printed when using pytest-mongodb with latest pymongo.  
Replacing `insert` with `insert_one` may fix  this issue, I have created a pull request for this.  

thank you for response. @mdomke
