### ISSUE TITLE
collection_names is deprecated

### ISSUE THREAD

**Issue by ulyssejdv** [mdomke/humongous#17]
https://github.com/mdomke/pytest-mongodb/blob/1cf1f1c6798c8debbebffd6c400efd74251dccf0/pytest_mongodb/plugin.py#L80

> venv\lib\site-packages\mongomock\database.py:41: UserWarning: collection_names is deprecated. Use list_collection_names instead.
>     warnings.warn('collection_names is deprecated. Use list_collection_names instead.')

**Comment by jakobdo** [comment]
I think this issue is a mongomock issue and not pytest-mongodb issue.

**Comment by LaraEzarik** [comment]
@jakobdo This issue is in pytest-mongodb, the warning just comes from the `collection_names` method in mongomock but it is pytest-mongodb that is making the call to `collection_names` instead of `list_collection_names`

**Comment by mdomke** [comment]
This is fixed in the 2.2.0 release
