### ISSUE TITLE
UnicodeDecodeError when using python 3.5.2

### ISSUE THREAD

**Issue by iliakur** [mdomke/humongous#6]
Hi, is there!

Thanks very much for your module, it's very helpful for testing our backend :)

I noticed you only list support for Python <= 3.4. When I tried running the tests with 3.5, [this line](https://github.com/mdomke/pytest-mongodb/blob/develop/pytest_mongodb/plugin.py#L108) caused me trouble, just as described here:
http://stackoverflow.com/questions/35051867/json-load-function-give-strange-unicodedecodeerror-ascii-codec-cant-decod

I could add a PR for this specifically, but I guess that a more concerted effort might be needed to add full Python 3.5 support.
Thanks!

**Update**
So it turns out this error does _not_ occur with python 3.5.3, but does with 3.5.2...

**Comment by mdomke** [comment]
Feel free to create a PR for this issue.

**Comment by mdomke** [comment]
Fixed in version 2.1.0. Thanks again for the PR!
